services:
  server:
    build:
      context: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: production
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mysecretpassword
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
    ports:
      - 5050:5050
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

volumes:
  pgdata:
