-- Custom SQL migration file, put you code below! --
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Scarlet Violet 151';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Crown Zenith';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Crown Zenith Galarian Gallery';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Silver Tempest';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Silver Tempest Trainer Gallery';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Lost Origin';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Lost Origin Trainer Gallery';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Holiday Calendar 2022';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'McDonalds Match Battle';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'English Pokemon Go';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Astral Radiance';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Astral Radiance Trainer Gallery';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Brilliant Stars';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Brilliant Stars Trainer Gallery';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Fusion Strike';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Celebrations';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Evolving Skies';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Chilling Reign';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Battle Styles';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Shining Fates';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'McDonalds 25th Anniversary';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Vivid Voltage';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Champions Path';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Pokemon Futsal Promos';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Darkness Ablaze';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'Rebel Clash';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'English Sword Shield';
ALTER TYPE expansion_set ADD VALUE IF NOT EXISTS 'English Sword Shield Promos';
